### ISSUE TITLE
バトランレビュー

### ISSUE THREAD

**Issue by hisaju** [0028sato/runteq_PF01#72]
遅くなってしまい申し訳ございません。。
※ 確認後closeしてください

## サービスレビュー

* コンセプトとしては面白いと思います！
* UIが検索ベースになっているので、これだとECサイトのような印象を持ってしまうので、タイムラインベースのように新着が流れてくるところをトップに持ってきたほうがよいかと思います。
* またこの手のユーザ投稿型のものは、初期データがないと全く使われない状態になってしまうので、最初は知り合いなどにお願いするかご自身でコンテンツを集めてサービスとして見れる状態にしておく必要があるかなと思います。

## コードレビュー

https://github.com/0028sato/runteq_PF01/blob/b72357cc343fe6532ca1bb63585b0a13fa4da454/app/controllers/posts_controller.rb#L8-L11

この辺りはデータが増えたときにパフォーマンスが著しく落ちて困ると思うので、不要であれば消しておきましょう。使う場合も検索などで絞りこむ形で必要なものだけ取得する形にするといいですね。

* まだ途中かと思いますが、機能が単純になりそうな感じにも見えるので、就活対策としてコードが厚くなるようにロジックやアルゴリズムが入り込むような機能を考えて追加されるといいかなと思いました。
* 就活でも見栄えが重要になってくるので（トップページが分かりやすくまとまっていないと採用担当者にも触ってもらえないので）UIやデータを整えていただけたらと思います。
* system specをちゃんと書かれているのは素晴らしいです。

**Comment by 0028sato** [comment]
確認しました。レビューありがとうございます！。
